/** Frozen before controlled comparison. Last four cases are held out from initial tuning. */
export const NFL_QUALITY_CASES = [
  {id:'receiver_flexibility', complex:true, heldOut:false, question:'Assume Nabers is unavailable. Who should we investigate at receiver while protecting next-year flexibility? Compare outside options with using our roster.'},
  {id:'outside_prepared_names', complex:true, heldOut:false, question:'Investigate receivers outside the Giants, but exclude Christian Kirk, Jakobi Meyers, Courtland Sutton, Darnell Mooney and Malik Nabers. Compare useful options using the available production and contract evidence.'},
  {id:'strict_screen', complex:false, heldOut:false, question:'Show veteran interior offensive linemen on other teams with a current-team 2026 cap charge strictly below $5 million. Exclude Dallas. Explain what this screen tells us and what it does not.'},
  {id:'change_to_iol', complex:false, heldOut:false, question:'Drop the receiver search. Investigate interior offensive linemen outside NYG instead. Explain the first options worth checking and the missing cost information.'},
  {id:'internal_options', complex:false, heldOut:false, question:'Assume Nabers is unavailable. Use our internal receivers instead of acquiring someone. Who should we examine first, and what evidence would change that order?'},
  {id:'salary_conversion', complex:true, heldOut:false, question:'Model converting $6 million of Paulson Adebo’s 2026 salary after June 1. Assume $8 million of unpaid salary remains available. Explain current and future cap effects and whether cash changes.'},
  {id:'minimum_funding', complex:true, heldOut:false, question:'Using the saved hypothetical Jakobi Meyers contract, find the minimum single salary conversion with an $8 million 2026 cap budget and preserve a $2 million reserve. Protect Brian Burns. Assume Paulson Adebo has $8 million of unpaid 2026 salary available. Explain the binding constraint and future cost.'},
  {id:'saved_contract', complex:true, heldOut:false, question:'Use the saved hypothetical Jakobi Meyers contract with an $8 million cap budget and $2 million reserve. Retain protection for Brian Burns. Retrieve the exact terms before calculating; if no saved scenario is available, explain the useful next input without inventing a contract.'},
  {id:'edge_history', complex:true, heldOut:true, question:'How did the historical EDGE trade market change from 2015 through 2025? Use recorded transactions and explain the complete Brian Burns trade package as a comparable, not a current quote.'},
  {id:'college_role', complex:true, heldOut:true, question:'Compare Tyler Warren and Colston Loveland in the historical 2025 draft case for a receiving-first tight end role. These are illustrative user-supplied evaluations: receiving, Warren 8/10 and Loveland 9/10; movement blocking, Warren 9/10 and Loveland 6/10. Weight receiving 70% and movement blocking 30%. Separate these supplied grades from public evidence, explain the conditional choice, and what changes if movement blocking matters more.'},
  {id:'availability', complex:false, heldOut:true, question:'Using the historical Giants September 17–21, 2025 availability report, explain who warrants the most attention. Distinguish participation, designation and workload. What cannot be concluded about a trend or medical outlook?'},
  {id:'coaching', complex:true, heldOut:true, question:'Use the captured 2025 Weeks 1–3 Giants and Chiefs plays. Compare third-down passing on medium or long distances outside the red zone. Explain observed outcomes and which hypotheses require film.'},
] as const;
export const NFL_QUALITY_SEQUENCES = [
 {id:'scope', questions:[NFL_QUALITY_CASES[0].question,'Drop the receiver objective. Look at veteran interior offensive linemen outside NYG, strictly below $5 million current-team cap, excluding Dallas.','Use our own interior offensive line instead. The acquisition screen no longer applies. Explain the changed recommendation.']},
 {id:'funding',questions:[NFL_QUALITY_CASES[6].question,'Change the cap budget to $6 million and keep the $2 million reserve and Burns protection. Recalculate the minimum.','Now keep a $3 million reserve. What changes, and which player remains protected?']},
 {id:'saved',questions:['Use the saved hypothetical Jakobi Meyers contract. Apply an $8 million cap budget and $2 million reserve; protect Brian Burns. Explain whether funding is needed and retain the exact compensation.','What is the distinction between active contract term and guaranteed liability?','Use the same saved hypothetical Meyers terms, change only the cap budget to $7 million, and retain the reserve and Burns protection. Explain the changed result.']},
 {id:'history',questions:[NFL_QUALITY_CASES[8].question,'Narrow that to the Brian Burns package. Keep every pick on both sides and distinguish conditions from guaranteed assets.','Now compare that package with the historical Khalil Mack trade to Chicago. Keep each transaction’s actual year and complete package.']},
] as const;
