import type { NflAuthorityDomain, NflAuthorityPassage } from './types.js';

export interface NflAuthorityTopic {
  id: string;
  label: string;
  aliases: readonly string[];
  domains: readonly NflAuthorityDomain[];
  locators: readonly string[];
  terms: readonly string[];
  caveat?: string;
}

/** Search hints, never an alternative corpus of authored legal conclusions. */
export const NFL_AUTHORITY_TOPICS: readonly NflAuthorityTopic[] = [
  { id: 'guarantees', label: 'Guarantee protections and voiding', aliases: ['guarantee', 'guarantees', 'guaranteed', 'injury only', 'vesting', 'offset'], domains: ['cba'], locators: ['Contract language > Guaranteed money', 'Article 4, Section 9', 'Article 13, Section 6', 'Article 26, Section 9'], terms: ['guaranteed', 'skill', 'injury', 'cap', 'voiding', 'offset'], caveat: 'Full guarantees, injury-only protection, vesting, offsets and forfeiture are different questions. An individual player’s guarantees require the executed contract and amendments.' },
  { id: 'bonus_proration', label: 'Signing-bonus proration and conversion', aliases: ['proration', 'prorated', 'amortization', 'amortized', 'signing bonus', 'convert salary', 'salary into bonus', 'restructure', 'void years'], domains: ['cba'], locators: ['Article 13, Section 6'], terms: ['signing bonus', 'prorated', 'five years', 'amounts treated'], caveat: 'General cap accounting does not establish a unilateral restructure right or calculate savings without the player’s contract schedule.' },
  { id: 'june_1', label: 'June 1 release, trade and acceleration', aliases: ['june 1', 'june first', 'june 2', 'post june', 'pre june', 'dead money', 'acceleration', 'release versus trade', 'release vs trade'], domains: ['cba'], locators: ['Article 13, Section 6'], terms: ['June 1', 'June 2', 'acceleration', 'Final League Year'], caveat: 'Article 13 distinguishes actual post-June 1 trades from up to two qualifying advance termination designations, including timing and renegotiation conditions. Its Final League Year exception means the agreement’s final League Year, not the last year of a player’s contract.' },
  { id: 'practice_squad', label: 'Practice squads and elevations', aliases: ['practice squad', 'practice player', 'elevation', 'elevate', 'call up', 'callups'], domains: ['cba', 'league_dates'], locators: ['Article 33'], terms: ['practice squad', 'elevation', 'International Player'], caveat: 'The executed 2020 CBA’s practice-squad size and elevation provisions are a baseline. The 2026 calendar permits 17 practice-squad players when one qualifies and is designated as an International Player. Current eligibility, elevation limits and later amendments are not comprehensively verified here; do not apply original CBA limits as current policy.' },
  { id: 'waivers', label: 'Waiver eligibility and calendar', aliases: ['waiver', 'waivers', 'waived', 'claiming', 'veteran release', 'credited seasons'], domains: ['cba', 'league_dates'], locators: ['Article 29'], terms: ['waivers', 'credited', 'waiver', 'claiming'], caveat: 'Waiver eligibility depends on pension-credited service and timing. This index has no live waiver order, claim outcome or individual credited-service certification.' },
  { id: 'fifth_year_option', label: 'First-round fifth-year option', aliases: ['fifth year', '5th year', 'rookie option', 'first round option'], domains: ['cba'], locators: ['Article 7, Section 7'], terms: ['2018', 'option', 'guaranteed', 'exercise'], caveat: 'Article 7 contains separate treatment for the 2016–2017 draft classes and the 2018-and-later classes. Match the player’s draft class and clause before applying option guarantees, performance tiers or deadlines.' },
  { id: 'rookie_contracts', label: 'Rookie contracts and renegotiation', aliases: ['rookie contract', 'rookie extension', 'extend a rookie', 'renegotiate a rookie', 'undrafted rookie'], domains: ['cba', 'league_dates'], locators: ['Article 7, Section 3'], terms: ['renegotiated', 'third', 'second', 'rookie'], caveat: 'Drafted and undrafted rookie renegotiation timelines differ. Contract year, draft status, actual terms and applicable calendar entry remain necessary.' },
  { id: 'rfa_erfa', label: 'Restricted and exclusive-rights free agency', aliases: ['rfa', 'erfa', 'restricted free agent', 'restricted free agency', 'exclusive rights', 'original round', 'second round tender', 'right of first refusal'], domains: ['cba', 'league_dates'], locators: ['Article 8', 'Article 9, Section 2', 'Article 9, Section 3'], terms: ['restricted', 'qualifying', 'tender', 'accrued'], caveat: 'Tender eligibility and categories are indexed. Current tender dollar amounts, a player’s accrued seasons, and a live club tender are not inferred.' },
  { id: 'franchise_transition', label: 'Franchise and transition tenders', aliases: ['franchise', 'transition tag', 'transition tender', 'tag deadline', 'tenders', 'tender'], domains: ['cba', 'league_dates'], locators: ['Article 10'], terms: ['franchise', 'transition', 'tender', 'designation'], caveat: 'Tender formulas and dated deadlines do not establish current tender amounts or a player’s designation and signing status.' },
  { id: 'termination_pay', label: 'Veteran termination pay', aliases: ['termination pay', 'vested veteran', 'vested salary'], domains: ['cba'], locators: ['Article 30'], terms: ['termination', 'eligibility', 'regular season'], caveat: 'Termination pay is conditional and distinct from negotiated contract guarantees. Review the eligibility and ineligibility sections together.' },
  { id: 'incentives', label: 'LTBE and NLTBE incentives', aliases: ['ltbe', 'nltbe', 'incentive', 'incentives', 'likely to be earned'], domains: ['cba'], locators: ['Article 13, Section 6'], terms: ['incentives', 'likely', 'earned'], caveat: 'The agreement has incentive-specific exceptions and permitted categories. This retrieval does not calculate a player’s earned incentives or league adjustments.' },
  { id: 'injury_lists', label: 'PUP, NFI and injury protection', aliases: ['pup', 'nfi', 'physically unable', 'non football injury', 'injury protection', 'injured reserve'], domains: ['cba', 'league_dates'], locators: ['Article 20', 'Article 45'], terms: ['physically unable', 'injury', 'reserve'], caveat: 'A roster-list rule does not establish medical prognosis, return approval or a player’s salary entitlement. Current return procedures need current league verification.' },
  { id: 'compensatory', label: 'Compensatory draft selection provisions', aliases: ['compensatory', 'comp picks', 'comp pick'], domains: ['cba'], locators: ['Article 6, Section 10', 'Appendix V'], terms: ['compensatory', 'formula'], caveat: 'The formula text is indexed; current qualifying-free-agent inputs and projected or awarded picks are not.' },
  { id: 'onside_kick', label: '2026 onside kicks', aliases: ['onside', 'surprise kick'], domains: ['playing_rules'], locators: ['Rule 6, Section 1, Article 6', 'Rule 6, Section 2, Article 5'], terms: ['onside', 'declare', 'receiving'], caveat: 'The 2026 edition changed when an onside kick may be declared. Formation, notification, recovery and penalty conditions still apply.' },
  { id: 'kickoff', label: 'Kickoffs, touchbacks and landing zone', aliases: ['kickoff', 'kick off', 'touchback', 'landing zone', 'safety kick'], domains: ['playing_rules'], locators: ['Rule 6, Section 1', 'Rule 6, Section 2'], terms: ['touchback', 'landing zone', '50-yard', 'kickoff'], caveat: 'Kickoff touchback outcomes depend on the kick’s origin, first touch and subsequent path; the 2026 50-yard-line exception is indexed.' },
  { id: 'catch', label: 'Completed catches and possession', aliases: ['catch', 'caught', 'two feet', 'one foot', 'toe tap', 'heel'], domains: ['playing_rules'], locators: ['Rule 8, Section 1, Article 3'], terms: ['control', 'inbounds', 'feet', 'catch'], caveat: 'A scenario requires the complete possession, inbounds and football-act facts. Retrieved text is not an official ruling on unobserved video.' },
  { id: 'overtime', label: 'Regular-season and postseason overtime', aliases: ['overtime', 'extra period', 'sudden death'], domains: ['playing_rules'], locators: ['Rule 16'], terms: ['possession', 'regular season', 'postseason', 'touchdown'], caveat: 'The 2026 rules distinguish regular-season time limits from postseason procedures and include possession exceptions.' },
  { id: 'pass_interference', label: 'Pass interference', aliases: ['pass interference', 'dpi', 'opi', 'uncatchable'], domains: ['playing_rules'], locators: ['Rule 8, Section 5'], terms: ['interference', 'catchable', 'contact'], caveat: 'Timing, catchability, ball location and permitted-contact exceptions matter to a pass-interference scenario.' },
  { id: 'grounding', label: 'Intentional grounding', aliases: ['grounding', 'throw away', 'throwaway', 'outside the pocket'], domains: ['playing_rules'], locators: ['Rule 8, Section 2'], terms: ['grounding', 'pocket', 'line of scrimmage'], caveat: 'Read the pocket, line-of-scrimmage, physical-contact and clock exceptions before applying the general grounding rule.' },
  { id: 'replay', label: 'Replay and challenges', aliases: ['replay', 'challenge', 'reviewable', 'booth review'], domains: ['playing_rules'], locators: ['Rule 15'], terms: ['review', 'challenge', 'replay'], caveat: 'Reviewability and who may initiate a review depend on the game situation and specific ruling.' },
  { id: 'league_deadlines', label: 'Captured league calendar', aliases: ['deadline', 'important dates', 'league year begins', 'league year start', 'free agency begins', 'roster cutdown', 'trading ends', 'trade window'], domains: ['league_dates'], locators: ['Calendar entry:'], terms: ['deadline', 'trading', 'begins', 'reduce', 'rosters'], caveat: 'The captured rolling calendar starts in July 2026 and extends into May 2027. Dates outside its captured entries are not inferred; all times are Eastern and dates may change.' },
] as const;

export function topicAppliesToPassage(topic: NflAuthorityTopic, passage: NflAuthorityPassage): boolean {
  if (!topic.domains.includes(passage.domain)) return false;
  return passage.domain === 'league_dates'
    ? topic.terms.some(term => passage.text.toLowerCase().includes(term.toLowerCase()))
    : topic.locators.some(location => passage.locator === location || passage.locator.startsWith(`${location},`));
}
